/* HTTP status codes */
module.exports.SERVER_UNAUTHORIZED_CODE = 401;
module.exports.SERVER_ERROR_HTTP_CODE = 412;
module.exports.SERVER_NOT_ALLOWED_HTTP_CODE = 503;
module.exports.SERVER_OK_HTTP_CODE = 200;
module.exports.SERVER_NOT_FOUND_HTTP_CODE = 404;
module.exports.SERVER_INTERNAL_ERROR_HTTP_CODE = 500;

/* ERROR CODES */
module.exports.MISSING_PARAMETER = "MISSING_PARAMETER";
module.exports.ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND";
module.exports.INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
module.exports.SEQUELIZE_ERROR = "SEQUELIZE_ERROR";
module.exports.AXIOS_ERROR = "AXIOS_ERROR";
